package com.zzhen.app.passfree.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzhen.app.passfree.entity.Code;
import com.zzhen.app.passfree.entity.User;

import com.zzhen.app.passfree.dao.CodeDao;
import com.zzhen.app.passfree.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig codeDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CodeDao codeDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        codeDaoConfig = daoConfigMap.get(CodeDao.class).clone();
        codeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        codeDao = new CodeDao(codeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Code.class, codeDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        codeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CodeDao getCodeDao() {
        return codeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
